### ISSUE TITLE
No Team found! Make sure the token you provided is valid and that the team’s slug correspond to the one you see in Vercel

### ISSUE THREAD

**Issue by theslowdown** [ndimatteo/sanity-plugin-vercel-deploy#17]
```
No Team found!
Make sure the token you provided is valid and that the team’s slug correspond to the one you see in Vercel
```

Getting this error (Sanity badge, bottom right corner) and can't get to create my first deploy.

Maybe related to https://vercel.com/changelog/ui-hooks-for-integrations-will-be-deprecated ?

**Comment by ndimatteo** [comment]
Hey there @theslowdown sorry for the delay in getting back to you!

I don't think this is related to the link you sent. That's for Vercel integrations on the Vercel platform. We're not using their integrations API or webhooks.

It sounds like your team slug is not valid. You can see that error is generated from here: https://github.com/ndimatteo/sanity-plugin-vercel-deploy/blob/28918a5cd2e034109074665d293d371574e6545e/src/vercel-deploy.js#L75-L88

You'll want to make sure you only enter in a team slug if the project is part of a team account.

If you're still getting this error, can you open up the browser console to see what error is output there?

**Comment by Symasia** [comment]
Apologies in advance for writing this into a closed issue, but I came across this exact problem today. The slug didn't do the trick, I had to add the team ID which currently follows a format of <team_xxx> which can be found under the team settings. I inspected the response from the request made to the Vercel API, and it implied both the slug and the ID works which is why I tried it.

Could be that Vercel made some changes to the API? Might be worth looking into.

**Comment by ndimatteo** [comment]
Hey there @Symasia, no problem at all, you actually illuminated what the problem was!

It looks like that while they do still accept both the team `id` and `slug`, if you want to use the `slug` it's only accepted as a query parameter, not as the path parameter.

I just fixed this and published the change so that you can use the slug as intended in v`2.1.6`

You should be all set now, but feel free to open another issue if anything else comes up! 🤘

**Comment by jscarpelli3** [comment]
hello!  Really have appreciated this plugin!  

Recently i started getting this error on a studio built for a client.  I'm not sure it is preventing deployments... just dont want them seeing an error all the time.   tried making a new token, but I cannot update the current deploy button with it because it says it can't find the team.  

i'm on the latest version of the plugin.  thanks ahead of time!

**Comment by ndimatteo** [comment]
@jscarpelli3 I've had clients change their team name in the past which can cause issues like this. Can you check with the client's vercel account to see if anything has changed?

You should be able to update any setting for a deployment, except the Token.

**Comment by jscarpelli3** [comment]
Ok great thanks for your help.  Seems like they didn't know where to find the token... and it had expired.  (i was trying top update the hook, btw, not the token).  THanks again. great work on this plug in!
