### ISSUE TITLE
@sanity/dashboard depency missing

### ISSUE THREAD

**Issue by djfarly** [ndimatteo/sanity-plugin-vercel-deploy#2]
Hej, thank you for the project - it is basically exactly what I was looking for!

When first installing on a fresh sanity install you'll get:

```
sanity start
✔ Checking configuration files...
⠧ Compiling...webpack built d029d1460e2bc3cfd470 in 21713ms
✔ Compiling...
Failed to compile.

Error in ../node_modules/@sanity/css-loader?modules&localIdentName=[name]_[local]_[hash:base64:5]&importLoaders=1&sourceMap!../node_modules/postcss-loader/lib??ref--1-oneOf-1-2!../node_modules/sanity-plugin-vercel-deploy/dist/vercel-deploy.css
Module not found: Error: Part "part:@sanity/dashboard/widget-styles" not implemented by any plugins
```

Just doing `sanity install @sanity/dashboard` fixes the problem.

*sanity versions*
```
@sanity/cli             2.0.5 (latest: 2.1.0)
@sanity/base            2.1.2 (up to date)
@sanity/cli             2.1.0 (up to date)
@sanity/components      2.1.0 (up to date)
@sanity/core            2.1.2 (up to date)
@sanity/dashboard       2.1.0 (up to date) <-- well afterwards :D
@sanity/default-layout  2.1.2 (up to date)
@sanity/default-login   2.1.0 (up to date)
@sanity/desk-tool       2.1.2 (up to date)
@sanity/vision          2.0.9 (latest: 2.1.0)
```

I reckon one could add `@sanity/dashboard` as a plugin of this plugin + maybe a peer dep.

Cheers!

**Comment by ndimatteo** [comment]
Glad you like it @djfarly !

This is interesting as it's already included as a peer dependency.

It's my understanding that those need to be installed separately? Looking at other sanity plugins, references to @sanity packages seem to always reside in the `peerDependencies` object, but perhaps I'm misunderstanding how these need to be referenced.

**Comment by djfarly** [comment]
Oops - maybe I just overlooked the output when installing. 🙈 
A thing I've often seen is to have peer dependencies - that are not there by default - noted in the docs somehow.

**Comment by eivindml** [comment]
<img width="1083" alt="Skjermbilde 2021-01-15 kl  22 19 10" src="https://user-images.githubusercontent.com/202450/104779714-e0dd6180-577f-11eb-8635-cb1f1dbb9994.png">

My studio crashed after installing this plugin, and it took some time to figure out the issue. So this should probably be added or something?

**Comment by ndimatteo** [comment]
Hey there @eivindml!

Would you mind elaborating on what the fix was for you? It's a bit hard to tell from your screenshot, but it sounds like it was having trouble finding: `part:@sanity/dashboard/widget-styles`

The `dashboard` component is referenced here: https://github.com/ndimatteo/sanity-plugin-vercel-deploy/blob/master/package.json#L41

Based on the review of official Sanity plugins, any dependencies of `@sanity` parts are seemingly always referenced as `peerDependencies `. Packages in this group are **not** automatically installed and will need to already be present in your Studio or manually installed. This might explain why you got the error.

What's confusing to me, is how this part wouldn't already be there for any Sanity studio, given that it's used for other core dashboard components. Perhaps I'm missing something, but open to suggestions if there's a better solution for how to include automatically when the plugin is installed.

I'll reach out to the Sanity folks in the meantime to see if there's some insight they can provide as well!

**Comment by eivindml** [comment]
Thanks for quick reply. :) I don't use dashboard that much (or at all), so this plugin was the first to require it.

I see the issue, and not sure what the solution should be. Maybe Sanity should do some warning or something when installing a plugin. Either way it created confusion for me and OP, and maybe others too.
