### ISSUE TITLE
Deploys from Sanity not clearing cache

### ISSUE THREAD

**Issue by samuelgoddard** [ndimatteo/sanity-plugin-vercel-deploy#26]
Hey! First off, thanks so much for the plugin, I use it on pretty much all of my projects and it's been great. Since last week i've noticed that deploys from within the studio don't seem to clear the build cache and the new content isn't actually being loaded into the site once deployed. Any idea what may be causing this? If I build the same deploy from within Vercel it works fine.

Cheers!

**Comment by ovsw** [comment]
As far as I know from reading the Vercel docs here https://vercel.com/docs/concepts/git/deploy-hooks#build-cache the build cache is used automatically for builds triggered via hooks. 
You have to appenm `?buildCache=false` to the hook request to clear the cache. 

So, you just need to create a new Deployment from the sanity admin panel (since you can't edit an existing one) and when pasting in your deploy hook from Vercel, just append the `?buildCache=false` part to it. Rest of the settings can be as in the initial deploy.

**Comment by ndimatteo** [comment]
Hey there @samuelgoddard sorry I never followed back up on this, but it seems like this is something that can be dealt with in the setup of each deployment by appending `?buildCache=false` to the hook URL.

Feel free to let me know if you think this should be handled a different way, or if there are still issues!
